name: Verify SemVer in PR Title
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  verify-semver-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR title
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          case "$TITLE" in
            major:\ *|minor:\ *|patch:\ *) exit 0 ;;
            *)
              echo "PR title must start with 'major:', 'minor:' or 'patch:'";
              exit 1 ;;
          esac
